---

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: sbwise01.aqha-ansible-bootstrap }
    - { role: sbwise01.aqha-example-web-app,
        deploy_mode: 'BAKE'
      }
